apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: beacon
    name: beacon
spec:
    ports:
        - name: "4000"
          port: 4000
          targetPort: 4000
        - name: "13000"
          port: 13000
          targetPort: 13000
        - name: "12000"
          port: 12000
          protocol: UDP
          targetPort: 12000
    selector:
        io.kompose.service: beacon
