apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        io.kompose.service: beacon-claim1
    name: beacon-claim1
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
