apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        io.kompose.service: beacon-claim0
    name: beacon-claim0
spec:
    accessModes:
        - ReadOnlyMany
    resources:
        requests:
            storage: 100Mi
