apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
    labels:
        io.kompose.service: beacon
    name: beacon
spec:
    lookupPolicy:
        local: false
    tags:
        - from:
              kind: DockerImage
              name: "gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-c59edb"
          name: ""
          referencePolicy:
              type: ""
