apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: geth
    name: geth
spec:
    ports:
        - name: "30303"
          port: 30303
          targetPort: 30303
        - name: 30303-udp
          port: 30303
          protocol: UDP
          targetPort: 30303
        - name: "8545"
          port: 8545
          targetPort: 8545
    selector:
        io.kompose.service: geth
status:
    loadBalancer: {}
