apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
    labels:
        io.kompose.service: geth
    name: geth
spec:
    lookupPolicy:
        local: false
    tags:
        - from:
              kind: DockerImage
              name: ethereum/client-go:v1.9.14
          name: v1.9.14
          referencePolicy:
              type: ""
