apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: geth
    name: geth
spec:
    replicas: 1
    selector:
        io.kompose.service: geth
    strategy:
        resources: {}
        type: Recreate
    template:
        metadata:
            creationTimestamp: null
            labels:
                io-kompose-network-default: "true"
                io-kompose-network-stereum-admin: "true"
                io.kompose.service: geth
        spec:
            containers:
                - args:
                      - --http
                      - --http.port=8545
                      - --http.addr=0.0.0.0
                      - --http.vhosts=*
                      - --allow-insecure-unlock
                      - --http.api=db,eth,net,web3,personal
                  image: " "
                  name: geth
                  ports:
                      - containerPort: 30303
                      - containerPort: 30303
                        protocol: UDP
                      - containerPort: 8545
                  resources:
                      limits:
                          cpu: "4"
                          memory: "10737418240"
                  volumeMounts:
                      - mountPath: /root/.ethereum
                        name: geth-claim0
            restartPolicy: Always
            terminationGracePeriodSeconds: 300
            volumes:
                - name: geth-claim0
                  persistentVolumeClaim:
                      claimName: geth-claim0
    test: false
    triggers:
        - type: ConfigChange
        - imageChangeParams:
              automatic: true
              containerNames:
                  - geth
              from:
                  kind: ImageStreamTag
                  name: geth:v1.10.8
          type: ImageChange
status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
