apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
    labels:
        io.kompose.service: geth
    name: geth
spec:
    replicas: 1
    selector:
        io.kompose.service: geth
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                io.kompose.network/downloads-default: "true"
                io.kompose.service: geth
        spec:
            containers:
                - args:
                      - --goerli
                      - --rpc
                      - --rpcport=8545
                      - --rpcaddr=0.0.0.0
                      - --rpcvhosts=*
                      - --allow-insecure-unlock
                      - --rpcapi=db,eth,net,web3,personal
                  image: " "
                  name: geth
                  ports:
                      - containerPort: 30303
                        hostPort: 30303
                        protocol: TCP
                      - containerPort: 30303
                        hostPort: 30303
                        protocol: UDP
                      - containerPort: 8545
                        hostIP: 127.0.0.1
                        hostPort: 8545
                        protocol: TCP
                  volumeMounts:
                      - mountPath: /root/.ethereum
                        name: geth-claim0
            hostname: geth
            restartPolicy: Always
            volumes:
                - name: geth-claim0
                  persistentVolumeClaim:
                      claimName: geth-claim0
    test: false
    triggers:
        - type: ConfigChange
        - imageChangeParams:
              automatic: true
              containerNames:
                  - geth
              from:
                  kind: ImageStreamTag
                  name: geth:v1.9.14
          type: ImageChange
