apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        io.kompose.service: geth-claim0
    name: geth-claim0
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 700Gi
