apiVersion: v1
kind: Pod
metadata:
    labels:
        io.kompose.network/downloads-default: "true"
        io.kompose.service: grafana
    name: grafana
spec:
    containers:
        - image: grafana/grafana:7.0.3
          name: grafana
          ports:
              - containerPort: 3000
                hostIP: 127.0.0.1
                hostPort: 3000
                protocol: TCP
          volumeMounts:
              - mountPath: /etc/grafana/provisioning
                name: grafana-claim0
              - mountPath: /var/lib/grafana
                name: grafana-data
    hostname: grafana
    restartPolicy: OnFailure
    volumes:
        - name: grafana-claim0
          persistentVolumeClaim:
              claimName: grafana-claim0
        - name: grafana-data
          persistentVolumeClaim:
              claimName: grafana-data
