apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: lighthouse-beacon
    name: lighthouse-beacon
spec:
    ports:
        - name: "5052"
          port: 5052
          targetPort: 5052
        - name: "8910"
          port: 8910
          targetPort: 5054
        - name: "9000"
          port: 9000
          targetPort: 9000
        - name: 9000-udp
          port: 9000
          protocol: UDP
          targetPort: 9000
    selector:
        io.kompose.service: lighthouse-beacon
status:
    loadBalancer: {}
