apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: lighthouse-beacon
    name: lighthouse-beacon
spec:
    lookupPolicy:
        local: false
    tags:
        - annotations: null
          from:
              kind: DockerImage
              name: stereum/lighthouse:v1.5.0-43
          generation: null
          importPolicy: {}
          name: ""
          referencePolicy:
              type: ""
status:
    dockerImageRepository: ""
