apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: lighthouse-beacon-claim0
    name: lighthouse-beacon-claim0
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
status: {}
