apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: lodestar-beacon-claim2
    name: lodestar-beacon-claim2
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
status: {}
