apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: nimbus-beacon
    name: nimbus-beacon
spec:
    lookupPolicy:
        local: false
    tags:
        - annotations: null
          from:
              kind: DockerImage
              name: stereum/nimbus:v1.4.2-33
          generation: null
          importPolicy: {}
          name: ""
          referencePolicy:
              type: ""
status:
    dockerImageRepository: ""
