apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: prysm-beacon-claim0
    name: prysm-beacon-claim0
spec:
    accessModes:
        - ReadOnlyMany
    resources:
        requests:
            storage: 100Mi
status: {}
