apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: prysm-beacon
    name: prysm-beacon
spec:
    lookupPolicy:
        local: false
    tags:
        - annotations: null
          from:
              kind: DockerImage
              name: gcr.io/prysmaticlabs/prysm/beacon-chain:v2.0.0-rc.0
          generation: null
          importPolicy: {}
          name: ""
          referencePolicy:
              type: ""
status:
    dockerImageRepository: ""
