apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: prysm-beacon
    name: prysm-beacon
spec:
    ports:
        - name: "4000"
          port: 4000
          targetPort: 4000
        - name: "8900"
          port: 8900
          targetPort: 8080
        - name: "13000"
          port: 13000
          targetPort: 13000
        - name: "12000"
          port: 12000
          protocol: UDP
          targetPort: 12000
    selector:
        io.kompose.service: prysm-beacon
status:
    loadBalancer: {}
