apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app: eth-cli
  name: lighthouse-claim
  namespace: ethernode
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    limits:
      storage: 200Gi
    requests:
      storage: 200Gi
  storageClassName: piraeus-storage
  volumeMode: Filesystem
