apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
    labels:
        io.kompose.service: slasher
    name: slasher
spec:
    lookupPolicy:
        local: false
    tags:
        - from:
            kind: DockerImage
            name: 'gcr.io/prysmaticlabs/prysm/slasher:'
          name: ""
          referencePolicy:
            type: ""
