apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: stereum-init-claim4
    name: stereum-init-claim4
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
status: {}
