---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: geth-sync
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 64Gi
    storageClassName: ocs-storagecluster-cephfs
    volumeMode: Filesystem
