apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: teku-beacon
    name: teku-beacon
spec:
    lookupPolicy:
        local: false
    tags:
        - annotations: null
          from:
              kind: DockerImage
              name: consensys/teku:21.8.1
          generation: null
          importPolicy: {}
          name: ""
          referencePolicy:
              type: ""
status:
    dockerImageRepository: ""
