apiVersion: v1
kind: Pod
metadata:
    labels:
        io.kompose.network/downloads-default: "true"
        io.kompose.service: validator
    name: validator
spec:
    containers:
        - args:
            - --config-file=/config/validator.yaml
          image: 'gcr.io/prysmaticlabs/prysm/validator:'
          name: validator
          volumeMounts:
            - mountPath: /config/validator.yaml
              name: validator-claim0
              readOnly: true
            - mountPath: /data
              name: validator-claim1
    hostname: validator
    restartPolicy: OnFailure
    volumes:
        - name: validator-claim0
          persistentVolumeClaim:
            claimName: validator-claim0
            readOnly: true
        - name: validator-claim1
          persistentVolumeClaim:
            claimName: validator-claim1
